### ISSUE TITLE
Any interest in turning the code into typescript modules?

### ISSUE THREAD

**Issue by Darkade** [Tetragramm/Tetragramm.github.io#4]
Hi! I'm doing some tests with the plane builder code and I'm making some significant changes to convert a lot of it into modules. So far I got working `PlaneBuilder/impl` at least for my minor tests

Possible benefits for the project at large would be automated deployments with webpack or other bundlers, as well as clearer dependencies and namespaces

My ultimate personal goal is to get the `InteractiveDash` from `PlaneBuilder/disp` working in this way because I want to go straight from the planebuilder link to all the numbers used in the interative dashboard

Thanks!

You can check some of the changes in this commit https://github.com/Darkade/Tetragramm.github.io/commit/9c5599caf1c880dcd4f2ce7e9b69f262363a423c

**Comment by Tetragramm** [comment]
I like the idea, and I'd love to help.  I note some issues with the find/replace or automated tool you've used so far.  Replacing every var with const, for one, doesn't work when a fair number are not actually const.

This looks like modularization method I've tried before, but I freely admit I don't know what I'm doing with modules.  So if you're willing to provide advice, I'm happy to try again.

**Comment by Darkade** [comment]
Nice! Yes, the codebase is kind of large but at least for the PlaneBuilder => InteractiveDash flow that I want to to reach I think I'll touch on many different functions and classes: It imports from `impl` `enginebuilder` and `disp` so I probably could show you an mvp of modules and a bundler so that you can decide if it's worth implementing further :3
 
Yup, in general I turned every `var` into `const` and looked for compiler warnings in order to change to `let` but a note is that `const` weirdly, means "not assigned ever again" so not to the left of an `=` sign. It does not "immutable" which is something I learnt from the compiler itself, so many times we think it should be `let` the compiler says that it should be `const`, like arrays that are initialized to `[]`and are later added to with `.push` 🤷🏽‍♀️ 

I have a while today to see if I can get the basic airplane full flow and I'll let you know!

**Comment by Darkade** [comment]
Right now I'm a bit stuck with the class `Aircraft_HTML` because it gets and sets some values in the html, so I'm going to check on that so that the class is able to work a bit more standalone, and then be plugged into a view controller or something :3 👍🏽 I'll let you know

**Comment by Tetragramm** [comment]
Ideally, all the aircraft calculations are in impl/Aircraft.ts and the other impl/* files, and disp/* is what interacts with the browser and HTML.  
I did bleed those together a bit in Aircraft_HTML though, so you're right, the things like generating the Cards, and the Interactive JSON would probably benefit from being separated out.
